#!/bin/sh
 
KERNEL_VERSION_FULL=$(uname -sr)
KERNEL_VERSION_NUMBER=$(uname -r)

MODULE_PATH="/lib/modules/$KERNEL_VERSION_NUMBER/kernel/drivers/char/joystick"

echo "Compiling DDR mat driver module for $KERNEL_VERSION_FULL" 
gcc -D__KERNEL__ -I/usr/src/linux/include -Wall -Wstrict-prototypes -Wno-trigraphs -O2 -fomit-frame-pointer -fno-strict-aliasing -fno-common -pipe -mpreferred-stack-boundary=2 -malign-functions=4 -DMODULE -DMODVERSIONS -include /usr/src/linux/include/linux/modversions.h \
-c -o ddrmat.o ddrmat.c

echo "Installing module in $MODULE_PATH"
cp ddrmat.o $MODULE_PATH

echo "Running depmod"
depmod -ae

echo "Going ahead and modprobe'ing the module..."
modprobe ddrmat gc=0,7

echo "DONE!!!"
