# Constants that a lot of things in pyDDR use.

from pygame.locals import *

E_PASS,E_QUIT,E_LEFT1,E_RIGHT1,E_UP1,E_DOWN1,E_FULLSCREEN,E_START1,E_SCREENSHOT,E_HCENTER,E_VCENTER,E_PGUP,E_PGDN,E_LEFT2,E_RIGHT2,E_UP2,E_DOWN2,E_START2,E_SELECT = range(19)
