MANPAGES += docs/man
UTILS += utils/dwi2step.py utils/findbpm.py utils/lyrictag.py utils/step2dwi.py utils/stepshrink.py utils/msd2step.py
PYMODS += config.py announcer.py fontfx.py input.py constants.py menus.py menudriver.py spritelib.py gfxtheme.py
DATA += themes images sound

clean:
	rm -f *.pyc

distclean: clean
	rm -f pyddr.cfg Makefile

cvsclean: distclean
	rm -rf CVS */CVS */*/CVS */*/*/CVS */*/*/*/CVS menuhelp

doc:
	lynx -dump docs/README.html > README
