.TH dwi2step 1 "January 16th, 2003"
.SH NAME
dwi2step \- convert DWI files to pyDDR step files
.br
msd2step \- convert MSD files to pyDDR stepfiles
.br
step2dwi \- convert step files files to DWI files
.SH SYNOPSIS
\fBdwi2step \fIfilename.dwi\fR
.br
\fBmsd2step \fIfilename.msd\fR
.br
\fBstep2dwi \fIfilename.step\fR
.SH DESCRIPTION
These scripts convert the popular DWI ("Dance With Intensity", a Windows
DDR simulator) and MSD file formats into the step format used by pyDDR, and
back again. It is capable of converting all the various note types (4th,
8th, 16th, 24th,  32nd, and 64th), as well as freeze arrows (also known as
hold arrows).
.PP
After running this script, manual tweaking of the offset field in the
file may still be necessary.
.SH BUGS
BPM changes are performed at your own risk.
.PP
Certain features in step files are not present in DWI files, and so can't
be converted back in the \fBstep2dwi\fR process.
.PP
All step data for each difficulty must be in the same line for dwi2step to
convert it. Many DWI files require manual editing for this to be the case.
.SH AUTHOR
Brendan Becker <tgz@orotech.net> is the primary author of pyDDR. Joe
Wreschnig <piman@debian.org> is the maintainer of pyDDR for Debian and the
author of this manual page.
.SH SEE ALSO
\fBpyddr\fR(6)
