.TH pydance 6 "June 2nd, 2003"
.SH NAME
pydance \- a dancing simulator game
.SH SYNOPSIS
\fBpydance\fR
.SH DESCRIPTION
pydance is much like the popular arcade game "Dance Dance Revolution", in
which you stand on a mat on the floor, with 4 buttons pointing forward,
backwards, left, and right. Arrows scroll across the screen, and you must
step on the arrows on the mat when they reach the top. These steps
happen in time with music in the background, causing a rough approximation
of dancing.
.PP
pydance supports most of the features of similar games, such as background
and banner images for each song, multiple difficulty levels, freeze
arrows (arrows you have to remain standing on for a length of time), BPM
changes and stops, and lyric display. pydance also allows you to use a real
DDR mat if you have a Playstation to PC joystick adapter supported by the
ddrmat kernel module for Linux (which is a modified version of the gamecon
kernel module), or a Playstation to USB joystick adapter and the USB
joystick driver, for any OS. If you lack a mat, you can play on the
keyboard, but it's much less fun.
.PP
You can also make your own step files to new music, in pydance's \fB.dance\fR
format. \fIdance-spec.txt\fR included with pydance documents this format.
pydance can also read its legacy \fB.step\fR format, and the popular Windows
\fB.dwi\fR and \fB.sm\fR formats.
.SH USAGE
The first player's arrows and settings are controlled by the I, J, K, and L
keys, and the second player's by the arrow keys. Letting the game wait on
the song selection screen will display help messages on the sidebar.
.PP
pydance is documented more completely in the \fIREADME.html\fR file included
with it.
.SH FILES
.IP /usr/share/games/pydance/songs,\ /usr/local/share/games/pydance/songs,\ ~/.pydance/songs
By default, pydance will look in these directories for your songs, step files,
and other game data. You can configure this with the \fBsongdir\fR
option in your pydance.cfg file.
.PP
Note that for DWI files, you will need to put everything (the music file,
lyric file, background, and banner) in its own separate directory, and
that directory inside \fIanother\fR subdirectory in the \fIsongs\fR
folder. This is a limitation of the DWI format; it uses its path name
and files in the same directory, rather than specifying things in the
file itself like \fB.dance\fR does.
.IP /etc/pydance.cfg,\ ~/.pydance/pydance.cfg
pydance configuration files. The settings in your local one override
the system-wide settings.
.IP /usr/share/games/pydance
Various data needed by pydance, such as background music and Python modules.
.SH AUTHORS
Brendan Becker <tgz@orotech.net> and Joe Wreschnig <piman@debian.org>,
with help from many others.
.SH SEE ALSO
\fBfindbpm\fR(1),
README.html included with pydance,
dance-spec.txt included with pydance.
